
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 25 18:29:56 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 49;
  public static final int FINALL = 47;
  public static final int PLUSPLUS = 8;
  public static final int JEDNAKOJEDNAKO = 37;
  public static final int OTVORENA_UGLASTA = 33;
  public static final int CONST = 35;
  public static final int ZAREZ = 22;
  public static final int DESNA_VITICASTA = 17;
  public static final int LEVA_VITICASTA = 16;
  public static final int VECEJEDNAKO = 41;
  public static final int TACKAZAREZ = 6;
  public static final int CONTINUE = 32;
  public static final int NUM_CONST = 48;
  public static final int MINUS = 15;
  public static final int RAZLICITO = 38;
  public static final int RECORD = 31;
  public static final int PODELJENO = 14;
  public static final int MANJEJEDNAKO = 42;
  public static final int JEDNAKO = 7;
  public static final int CLASS = 36;
  public static final int II = 21;
  public static final int PLUS = 12;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 9;
  public static final int RETURN = 26;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int ZATVORENA_UGLASTA = 34;
  public static final int IDENT = 51;
  public static final int BREAK = 23;
  public static final int VOID = 19;
  public static final int LEVA_ZAGRADA = 3;
  public static final int POSTO = 30;
  public static final int MANJE = 40;
  public static final int ELSE = 11;
  public static final int VECE = 39;
  public static final int READ = 24;
  public static final int GOTO = 25;
  public static final int WHILE = 27;
  public static final int TACKA = 44;
  public static final int EXTENDS = 43;
  public static final int BOOL_CONST = 50;
  public static final int MAJMUN = 45;
  public static final int DVETACKE = 5;
  public static final int PUTA = 13;
  public static final int TRIPLUS = 46;
  public static final int PRINT = 28;
  public static final int ILI = 20;
  public static final int DO = 29;
  public static final int DESNA_ZAGRADA = 4;
}

