
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 21 23:22:26 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  public static final int PLUSPLUS = 8;
  public static final int ZAREZ = 24;
  public static final int DESNA_VITICASTA = 17;
  public static final int LEVA_VITICASTA = 16;
  public static final int CONTINUE = 35;
  public static final int TACKAZAREZ = 6;
  public static final int NUM_CONST = 19;
  public static final int MINUS = 15;
  public static final int RECORD = 34;
  public static final int PODELJENO = 14;
  public static final int JEDNAKO = 7;
  public static final int II = 23;
  public static final int PLUS = 12;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 9;
  public static final int RETURN = 28;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 36;
  public static final int IDENT = 37;
  public static final int BREAK = 25;
  public static final int VOID = 21;
  public static final int LEVA_ZAGRADA = 3;
  public static final int POSTO = 33;
  public static final int ELSE = 11;
  public static final int READ = 26;
  public static final int GOTO = 27;
  public static final int WHILE = 29;
  public static final int BOOL_CONST = 20;
  public static final int DVETACKE = 5;
  public static final int PUTA = 13;
  public static final int PRINT = 31;
  public static final int ILI = 22;
  public static final int DO = 32;
  public static final int DESNA_ZAGRADA = 4;
  public static final int CONST = 38;
}

